import { Text } from '@nextui-org/react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { GetStaticProps } from "next";
import { Index_Header, Index_Cards } from '@/components/Index_Components'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale!, ["common"])),
  },
});

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Find Me!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Index_Header />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <Text
            h1
            size={80}
            css={{
              textGradient: "45deg, $yellow600 -20%, $red600 100%",
            }}
            weight="bold">
            Find-Meへようこそ！
          </Text>
        </div>
        <Index_Cards />
      </main>
    </>
  )
}